[package]
name = "pga2d"
version = "0.1.0"
authors = ["Tom Cumming <mail@tomcumming.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
