[package]
name = "pga2d"
description = "Simple tools for 2 dimensional projective geometric algebra"
version = "0.0.1"
authors = ["Tom Cumming <mail@tomcumming.co.uk>"]
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/tomcumming/pga2d"

[dependencies]
